[[redirects]]
  from = "/make-colors-great-again"
  to = "/how-to-suck-less-at-colors"
  status = 301

[[redirects]]
  from = "/all-posts"
  to = "/articles"
  status = 301

[[redirects]]
  from = "/test-react-testing-library"
  to = "/beginner-guide-testing-react-apps"
  status = 301

[[redirects]]
  from = "/reusable-and-accessible-switch-vue/"
  to = "/how-to-build-reusable-and-accessible-switch-vue/"
  status = 301